Repository guessiwillbefine/measurement-service-app, pull requests merged in 2023-05, with the labels that each got.

#36 Hotfix/some machine changes
  ms-api/src/main/java/ua/ms/controller/MeasureController.java
  ms-api/src/main/java/ua/ms/entity/machine/dto/view/MachineView.java
  ms-api/src/main/java/ua/ms/service/MachineService.java
  ms-api/src/main/java/ua/ms/util/mapper/impl/MachineMapper.java
  ms-api/src/main/resources/application.yaml
  ms-api/src/main/resources/db/changelog/dataset/constants-dataset.xml
Labels: bug

#37 set up websocket, added service to work with it, + some needed config…
  ms-api/pom.xml
  ms-api/src/main/java/ua/ms/MsApiApplication.java
  ms-api/src/main/java/ua/ms/configuration/security/AuthManager.java
  ms-api/src/main/java/ua/ms/configuration/security/SecurityConfig.java
  ms-api/src/main/java/ua/ms/configuration/security/service/RegistrationService.java
  ms-api/src/main/java/ua/ms/configuration/security/util/CustomAccessDeniedHandler.java
  ms-api/src/main/java/ua/ms/configuration/security/util/JWTFilter.java
  ms-api/src/main/java/ua/ms/configuration/socket/WebSocketConfig.java
  ms-api/src/main/java/ua/ms/controller/socket/MeasureSocketController.java
  ms-api/src/main/java/ua/ms/entity/socket/MeasuresSocketDto.java
  ms-api/src/main/java/ua/ms/service/MachineService.java
  ms-api/src/main/java/ua/ms/service/MeasureService.java
  ms-api/src/main/java/ua/ms/service/SensorService.java
  ms-api/src/main/java/ua/ms/service/UserService.java
  ms-api/src/main/java/ua/ms/service/repository/MeasureRepository.java
  ms-api/src/main/java/ua/ms/service/repository/SensorRepository.java
  ms-api/src/main/java/ua/ms/service/socket/MeasureSocketService.java
  ms-api/src/main/java/ua/ms/service/socket/MeasureSocketServiceImpl.java
  ms-api/src/main/java/ua/ms/service/socket/SocketService.java
  ms-api/src/main/resources/application.yaml
  ms-api/src/main/resources/db/changelog/dataset/measure-dataset.xml
  ms-api/src/test/java/ua/ms/authentication/AuthServiceTest.java
  ms-api/src/test/java/ua/ms/controllers/MeasureControllerTest.java
  ms-api/src/test/java/ua/ms/services/MeasureServiceTest.java
  ms-api/src/test/java/ua/ms/services/SensorServiceTest.java
Labels: feature

#38 critical value for sensor
  ms-api/src/main/java/ua/ms/entity/measure/Measure.java
  ms-api/src/main/java/ua/ms/entity/measure/dto/view/MeasureView.java
  ms-api/src/main/java/ua/ms/entity/sensor/Sensor.java
  ms-api/src/main/java/ua/ms/entity/sensor/dto/SensorDto.java
  ms-api/src/main/java/ua/ms/entity/sensor/dto/view/SensorView.java
  ms-api/src/main/resources/application.yaml
  ms-api/src/main/resources/db/changelog/changelog.yaml
  ms-api/src/main/resources/db/changelog/changeset/critical-value-column.yaml
  ms-api/src/main/resources/db/changelog/dataset/sensor-dataset.xml
  ms-api/src/test/java/ua/ms/TestConstants.java
Labels: feature

#42 Sensor.find() return dto
  ms-api/src/main/java/ua/ms/controller/SensorController.java
  ms-api/src/main/java/ua/ms/service/SensorService.java
  ms-api/src/main/java/ua/ms/util/mapper/impl/SensorMapper.java
Labels: fix

#44 hotfix/null check for critical values
  ms-api/src/main/java/ua/ms/entity/measure/Measure.java
Labels: fix

#45 bugfix/add-critical-value-setter
  ms-api/src/main/java/ua/ms/service/SensorService.java
Labels: bug

#46 Feature/journal service
  .gitignore
  README.md
  e2e-tests/src/test/java/ms/e2e/AuthenticationTest.java
  e2e-tests/src/test/java/ms/e2e/FactoryTest.java
  e2e-tests/src/test/java/ms/e2e/UserTest.java
  journal-service/README.md
  journal-service/pom.xml
  journal-service/src/main/java/ua/ms/journal/configuration/JournalServiceConfiguration.java
  journal-service/src/main/java/ua/ms/journal/entity/Event.java
  journal-service/src/main/java/ua/ms/journal/entity/EventType.java
  journal-service/src/main/java/ua/ms/journal/entity/MongoEntity.java
  journal-service/src/main/java/ua/ms/journal/service/AbstractJournalService.java
  journal-service/src/main/java/ua/ms/journal/service/EventJournalService.java
  journal-service/src/main/java/ua/ms/journal/service/JournalService.java
  journal-service/src/main/java/ua/ms/journal/service/repo/EventRepository.java
  journal-service/src/main/resources/application.properties
  journal-service/src/test/java/EntityTest.java
  ms-api/pom.xml
  ms-api/src/main/java/ua/ms/MsApiApplication.java
  ms-api/src/main/java/ua/ms/configuration/security/AuthManager.java
  ms-api/src/main/java/ua/ms/service/UserService.java
  ms-api/src/main/java/ua/ms/util/journal/EventServiceImpl.java
  ms-api/src/main/resources/application.yaml
  ms-api/src/test/java/ua/ms/authentication/AuthManagerTest.java
  ms-api/src/test/java/ua/ms/controllers/AuthenticationControllerTest.java
  pom.xml
Labels: feature

#47 mail notification, new event types, additional configuration
  journal-service/src/main/java/ua/ms/journal/entity/AlertEvent.java
  journal-service/src/main/java/ua/ms/journal/entity/AuthenticationEvent.java
  journal-service/src/main/java/ua/ms/journal/entity/EventType.java
  journal-service/src/main/java/ua/ms/journal/service/AbstractJournalService.java
  journal-service/src/main/java/ua/ms/journal/service/EventJournalService.java
  journal-service/src/main/java/ua/ms/journal/service/repo/AuthorizationEventRepository.java
  journal-service/src/main/java/ua/ms/journal/service/repo/EventRepository.java
  journal-service/src/main/resources/application.properties
  journal-service/src/test/java/EntityTest.java
  ms-api/src/main/java/ua/ms/configuration/security/AuthManager.java
  ms-api/src/main/java/ua/ms/entity/measure/Measure.java
  ms-api/src/main/java/ua/ms/service/MeasureService.java
  ms-api/src/main/java/ua/ms/service/WorkShiftService.java
  ms-api/src/main/java/ua/ms/service/mq/MessageQueueProducer.java
  ms-api/src/main/java/ua/ms/service/mq/impl/mail/MailAlertDto.java
  ms-api/src/main/java/ua/ms/service/mq/impl/mail/MailAlertService.java
  ms-api/src/main/java/ua/ms/service/repository/WorkShiftRepository.java
  ms-api/src/main/java/ua/ms/util/ApplicationConstants.java
  ms-api/src/main/java/ua/ms/util/journal/EventServiceImpl.java
  ms-api/src/test/java/ua/ms/TestConstants.java
  ms-api/src/test/java/ua/ms/authentication/AuthManagerTest.java
  ms-api/src/test/java/ua/ms/controllers/AuthenticationControllerTest.java
  ms-api/src/test/java/ua/ms/services/MailAlertMessageQueueTest.java
  ms-api/src/test/java/ua/ms/services/MeasureServiceTest.java
  ms-consumer/pom.xml
  ms-consumer/src/main/java/ua/ms/configuration/AlertConfiguration.java
  ms-consumer/src/main/java/ua/ms/consumer/impl/AlertDto.java
  ms-consumer/src/main/java/ua/ms/consumer/impl/MailQueueConsumer.java
  ms-consumer/src/main/java/ua/ms/journal/ConsumerEventService.java
  ms-consumer/src/main/java/ua/ms/sender/sender/AbstractMailSender.java
  ms-consumer/src/main/java/ua/ms/sender/sender/Sender.java
  ms-consumer/src/main/java/ua/ms/sender/sender/impl/EmailSender.java
  ms-consumer/src/main/resources/application.yaml
Labels: feature

#48 Feature/some changes
  docker-compose.yml
  ms-api/src/main/java/ua/ms/controller/socket/MeasureSocketController.java
  ms-api/src/main/java/ua/ms/entity/measure/MeasureSystem.java
  ms-api/src/main/resources/db/changelog/dataset/constants-dataset.xml
  ms-api/src/main/resources/db/changelog/dataset/sensor-dataset.xml
Labels: feature
